---
version: '3.8'
services:
  postgres-write:
    image: postgres:14-alpine
    container_name: postgres-write
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db_write
      POSTGRES_REPLICATION_USER: repl_user
      POSTGRES_REPLICATION_PASSWORD: repl_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - db-write:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=5
               -c max_replication_slots=5
               -c hot_standby=off

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-server:7.0.1
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  debezium-connect:
    container_name: debezium-connect
    image: debezium/connect:2.5
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    depends_on:
      - kafka
      - postgres-write

  create-topics:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      /usr/bin/kafka-topics --create --bootstrap-server kafka:29092 --topic ReadWrite.event --partitions 1 --replication-factor 1

  postgres-read:
    image: postgres:14-alpine
    container_name: postgres-read
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db_read
    ports:
      - "5431:5432"
    volumes:
      - db-read:/var/lib/postgresql/data
#    command: >
#      postgres -c wal_level=replica
#               -c max_wal_senders=5
#               -c hot_standby=on

#  postgres-read:
#    image: postgres:14-alpine
#    container_name: postgres-read
#    restart: always
#    depends_on:
#      - postgres-write
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: db_read
#      POSTGRES_REPLICATION_USER: repl_user
#      POSTGRES_REPLICATION_PASSWORD: repl_password
#      POSTGRES_HOST_AUTH_METHOD: trust
#      PGDATA: c:/data/docker/postgresql/data
#    ports:
#      - "5431:5432"
#    volumes:
#      - c:/data/docker/postgresql/data:/var/lib/postgresql/data
#    command: >
#      bash -c "
#        rm -rf c:/data/docker/postgresql/data/* &&
#        PGPASSWORD=repl_password pg_basebackup -h postgres-write -U repl_user -D  c:/data/docker/postgresql/data -Fp -Xs -P -R &&
#        echo 'standby_mode = on' >>  c:/data/docker/postgresql/data/recovery.conf &&
#        echo 'primary_conninfo = \"host=postgres-write port=5432 user=repl_user password=repl_password\"' >>  c:/data/docker/postgresql/data/recovery.conf &&
#      echo 'primary_conninfo = 'host=postgres-write port=5432 user=repl_user password=repl_password sslmode=prefer' >>  c:/data/docker/postgresql/data/postgresql.conf "
##    command: >
##      bash -c "
##        rm -rf /data/docker/postgresql/data/* &&
##        chown -R 999:999 /data/docker/postgresql/data || { echo 'Failed to set ownership'; exit 1; } &&
##        PGPASSWORD=repl_password pg_basebackup -h postgres-write -U repl_user -D /data/docker/postgresql/data -Fp -Xs -P -R &&
##        echo 'standby_mode = on' >> /data/docker/postgresql/data/recovery.conf &&
##        echo 'primary_conninfo = \"host=postgres-write port=5432 user=repl_user password=repl_password\"' >> /data/docker/postgresql/data/recovery.conf"
##    command: >
##      bash -c "
##        rm -rf /var/lib/postgresql/data/* &&
##        chown -R 999:999 /var/lib/postgresql/data || { echo 'Failed to set ownership'; exit 1; } &&
##        PGPASSWORD=repl_password pg_basebackup -h postgres-write -U repl_user -D /var/lib/postgresql/data -Fp -Xs -P -R &&
##        echo 'standby_mode = on' >> /var/lib/postgresql/data/recovery.conf &&
##        exec su-exec postgres postgres"

volumes:
  db-write:
  db-read: