DROP TABLE IF EXISTS ACCESSCONFIG.APPLICATION_LAUNCH CASCADE;

CREATE TABLE IF NOT EXISTS ACCESSCONFIG.APPLICATION_LAUNCH
(
    APPLICATION_LAUNCH_ID UUID NOT NULL DEFAULT  gen_random_uuid(),
    APP_CODE            VARCHAR(32) NOT NULL,
    TOKEN               TEXT NOT NULL, -- Secured with BCrypt ,
    STATUS              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE
    BASE_URL            TEXT NOT NULL, -- Application launch URL Prefix
    CREATED_DATE        TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    LAST_UPDATED_DATE   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CREATED_BY          UUID NOT NULL,
    UPDATED_BY          UUID NOT NULL,

    CONSTRAINT APPLICATION_LAUNCH_ID_PK PRIMARY KEY (APPLICATION_LAUNCH_ID)
);


COMMENT ON TABLE ACCESSCONFIG.APPLICATION_LAUNCH
    IS 'Table to manage application launch configuration';

COMMENT ON COLUMN ACCESSCONFIG.APPLICATION_LAUNCH.APP_CODE
    IS 'Unique identifier for non-native applications';

COMMENT ON COLUMN ACCESSCONFIG.APPLICATION_LAUNCH.TOKEN
    IS 'Unique token for application launch';

COMMENT ON COLUMN ACCESSCONFIG.APPLICATION_LAUNCH.BASE_URL
    IS 'base-url of application to be launch';